
[cmd_duration]
min_time = 500
format = 'underwent [$duration](bold yellow)'

[directory]
truncation_length = 8
truncation_symbol = 'â€¦/'

[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 4
truncation_symbol = ''
#ignore_branches = ['master', 'main']

[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[c]
format = 'via [$name $version]($style)'

[haskell]
format = 'via [$symbol($version )]($style)'

[java]
symbol = 'â˜• '
style = 'red'

[lua]
format = 'via [ğŸŒ• $version](bold blue) '

[python]
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
