# Do not print a new line at teh start of the prompt
#add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[cmd_duration]
min_time = 500
show_milliseconds = true
format = 'took [$duration](bold yellow) '

[directory]
truncation_symbol = 'â€¦/'

#[env_var.USER]
#default = 'john doe'

[git_branch]
#symbol = 'ğŸŒ± '
symbol = ''
#truncation_symbol = ''

[git_commit]
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) on [$hostname](bold red)'
disabled = true

[jobs]
number_threshold = 4

[localip]
format = '@[$localipv4](bold red)'

[shell]
style = 'cyan bold'
disabled = false

[sudo]
symbol = 'root '
style = 'bold red'
disabled = false

[package]
disabled = true

[c]
format = 'via [$name $version]($style) '

[haskell]
format = 'via [$symbol($version )]($style)'

[java]
style = 'red'

[lua]
format = 'via [ğŸŒ• $version](bold blue) '

[python]
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
